// Code generated by "stringer -type Language -trimprefix=Lang"; DO NOT EDIT.

package dwarfy

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LangC89-1]
	_ = x[LangC-2]
	_ = x[LangAda83-3]
	_ = x[LangC_plus_plus-4]
	_ = x[LangCobol74-5]
	_ = x[LangCobol85-6]
	_ = x[LangFortran77-7]
	_ = x[LangFortran90-8]
	_ = x[LangPascal83-9]
	_ = x[LangModula2-10]
	_ = x[LangJava-11]
	_ = x[LangC99-12]
	_ = x[LangAda95-13]
	_ = x[LangFortran95-14]
	_ = x[LangPLI-15]
	_ = x[LangObjC-16]
	_ = x[LangObjC_plus_plus-17]
	_ = x[LangUPC-18]
	_ = x[LangD-19]
	_ = x[LangPython-20]
	_ = x[LangOpenCL-21]
	_ = x[LangGo-22]
	_ = x[LangModula3-23]
	_ = x[LangHaskell-24]
	_ = x[LangC_plus_plus_03-25]
	_ = x[LangC_plus_plus_11-26]
	_ = x[LangOCaml-27]
	_ = x[LangRust-28]
	_ = x[LangC11-29]
	_ = x[LangSwift-30]
	_ = x[LangJulia-31]
	_ = x[LangDylan-32]
	_ = x[LangC_plus_plus_14-33]
	_ = x[LangFortran03-34]
	_ = x[LangFortran08-35]
	_ = x[LangRenderScript-36]
	_ = x[LangBLISS-37]
	_ = x[Langlo_user-32768]
	_ = x[Langhi_user-65535]
}

const (
	_Language_name_0 = "C89CAda83C_plus_plusCobol74Cobol85Fortran77Fortran90Pascal83Modula2JavaC99Ada95Fortran95PLIObjCObjC_plus_plusUPCDPythonOpenCLGoModula3HaskellC_plus_plus_03C_plus_plus_11OCamlRustC11SwiftJuliaDylanC_plus_plus_14Fortran03Fortran08RenderScriptBLISS"
	_Language_name_1 = "lo_user"
	_Language_name_2 = "hi_user"
)

var (
	_Language_index_0 = [...]uint8{0, 3, 4, 9, 20, 27, 34, 43, 52, 60, 67, 71, 74, 79, 88, 91, 95, 109, 112, 113, 119, 125, 127, 134, 141, 155, 169, 174, 178, 181, 186, 191, 196, 210, 219, 228, 240, 245}
)

func (i Language) String() string {
	switch {
	case 1 <= i && i <= 37:
		i -= 1
		return _Language_name_0[_Language_index_0[i]:_Language_index_0[i+1]]
	case i == 32768:
		return _Language_name_1
	case i == 65535:
		return _Language_name_2
	default:
		return "Language(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
