language: c
dist: bionic
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gawk libsigsegv2 dwarfdump check libdwarf-dev libjson0-dev liburcu-dev
script: make all

