on: [push, pull_request]
name: BuildAndTest
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { go-version: 1.22.x, dwarf-version: 3}
          - { go-version: 1.22.x, dwarf-version: 4}
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: prerequisites # ubuntu speicific
      run: sudo apt-get install check
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Test
      env:
        GO111MODULE: on
      run: go test -cover ./...
    - name: Build
      run: go build
    - name: Examples test
      run: make test all DWARF_VER_FORCE=${{matrix.dwarf-version}}

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        go-version: [1.22.x] # , 1.21.x, 1.20.x]
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: prerequisites # macos speicific
      run: brew install pkg-config check
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Test
      env:
        GO111MODULE: on
      run: go test -cover ./...
    - name: Build
      run: go build
    - name: Examples test
      run: make test all

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - { go-version: 1.22.x, sys: mingw64, env: x86_64 }
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: prerequisites # Windows speicific
      uses: msys2/setup-msys2@v2 
      with:
        msystem: ${{matrix.sys}}
        update: true
        install: base-devel git pkg-config mingw-w64-${{matrix.env}}-check mingw-w64-${{matrix.env}}-toolchain
        path-type: inherit # to be able to find go
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Test
      env:
        GO111MODULE: on
      run: go test -cover ./...
    - name: Build
      run: go build
    - name: Examples test
      run: make test all